# Create proxy
- name: Run proxy
  docker_container:
    name: httptp3
    image: krateros/tp-devops-http-server:latest
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    pull: yes
    published_ports:
      - "80:80"
      - "8080:8081"
    networks:
      - name: outside
      - name: front