name: TP2 tests

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"

      - name: Build and test with Maven
        run: |
          set -e  # Ensures the script exits on failure
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=irc-adlen_Devops-CI-CD \
            -Dsonar.organization=irc-adlen \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            --file ./pom.xml
        working-directory: ./TP2/simple-api
